"""Add Bible models

Revision ID: 023d7c5f6a59
Revises: 4fecd8a1b8ca
Create Date: 2025-12-15 04:44:33.803090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023d7c5f6a59'
down_revision = '4fecd8a1b8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bible_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.Column('testament', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bible_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['bible_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bible_verses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['bible_chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bible_verses')
    op.drop_table('bible_chapters')
    op.drop_table('bible_books')
    # ### end Alembic commands ###
