"""add cover image to posts

Revision ID: ca8d22cadf07
Revises: fc04a0d541e5
Create Date: 2025-12-14 03:20:41.243728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8d22cadf07'
down_revision = 'fc04a0d541e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
